version: '3'
services:
  mysqldb:
    image: mysql:8.0.17
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_USER=dockeruser
      - MYSQL_PASSWORD=dockeruser
      - MYSQL_DATABASE=cp_dev
    networks:
      - carparknet
  app:
    build: .
    ports:
      - "3005:3005"
    depends_on:
      - mysqldb
    networks:
      - carparknet
networks:
  carparknet: