// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import govsgcarpark "github.com/dare-rider/carpark/app/extservices/govsgcarpark"
import mock "github.com/stretchr/testify/mock"

// RepoI is an autogenerated mock type for the RepoI type
type RepoI struct {
	mock.Mock
}

// CarparkAvailability provides a mock function with given fields:
func (_m *RepoI) CarparkAvailability() (*govsgcarpark.SuccessResp, error) {
	ret := _m.Called()

	var r0 *govsgcarpark.SuccessResp
	if rf, ok := ret.Get(0).(func() *govsgcarpark.SuccessResp); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*govsgcarpark.SuccessResp)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
