// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import carparkinfo "github.com/dare-rider/carpark/app/models/carparkinfo"

import mock "github.com/stretchr/testify/mock"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// CarparkInfos provides a mock function with given fields:
func (_m *Usecase) CarparkInfos() ([]carparkinfo.Model, error) {
	ret := _m.Called()

	var r0 []carparkinfo.Model
	if rf, ok := ret.Get(0).(func() []carparkinfo.Model); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]carparkinfo.Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
