// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import carpark "github.com/dare-rider/carpark/app/models/carpark"
import mock "github.com/stretchr/testify/mock"
import sqlx "github.com/jmoiron/sqlx"

// RepoI is an autogenerated mock type for the RepoI type
type RepoI struct {
	mock.Mock
}

// FetchNearest provides a mock function with given fields: currentDist, limit, offset
func (_m *RepoI) FetchNearest(currentDist float64, limit int, offset int) ([]carpark.Model, error) {
	ret := _m.Called(currentDist, limit, offset)

	var r0 []carpark.Model
	if rf, ok := ret.Get(0).(func(float64, int, int) []carpark.Model); ok {
		r0 = rf(currentDist, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]carpark.Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(float64, int, int) error); ok {
		r1 = rf(currentDist, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOrUpdate provides a mock function with given fields: mod, tx
func (_m *RepoI) InsertOrUpdate(mod *carpark.Model, tx ...*sqlx.Tx) error {
	_va := make([]interface{}, len(tx))
	for _i := range tx {
		_va[_i] = tx[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, mod)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*carpark.Model, ...*sqlx.Tx) error); ok {
		r0 = rf(mod, tx...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
