// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import carpark "github.com/dare-rider/carpark/app/models/carpark"
import mock "github.com/stretchr/testify/mock"
import requests "github.com/dare-rider/carpark/app/requests"
import sqlx "github.com/jmoiron/sqlx"

// Usecase is an autogenerated mock type for the Usecase type
type Usecase struct {
	mock.Mock
}

// FetchNearestWithInfo provides a mock function with given fields: req
func (_m *Usecase) FetchNearestWithInfo(req *requests.NearestCarparksRequest) ([]carpark.Model, error) {
	ret := _m.Called(req)

	var r0 []carpark.Model
	if rf, ok := ret.Get(0).(func(*requests.NearestCarparksRequest) []carpark.Model); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]carpark.Model)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*requests.NearestCarparksRequest) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertOrUpdate provides a mock function with given fields: mod, tx
func (_m *Usecase) InsertOrUpdate(mod *carpark.Model, tx ...*sqlx.Tx) error {
	_va := make([]interface{}, len(tx))
	for _i := range tx {
		_va[_i] = tx[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, mod)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(*carpark.Model, ...*sqlx.Tx) error); ok {
		r0 = rf(mod, tx...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LimitOffset provides a mock function with given fields: pgNo, perPg
func (_m *Usecase) LimitOffset(pgNo int, perPg int) (int, int) {
	ret := _m.Called(pgNo, perPg)

	var r0 int
	if rf, ok := ret.Get(0).(func(int, int) int); ok {
		r0 = rf(pgNo, perPg)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(int, int) int); ok {
		r1 = rf(pgNo, perPg)
	} else {
		r1 = ret.Get(1).(int)
	}

	return r0, r1
}
